import "dotenv/config";
import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";
import { properties } from "../src/db/schema";

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql);

const seed = [
  // ── Luxury ────────────────────────────────────────────────────────────────
  {
    title: "The Pinnacle Penthouse",
    description: "Breathtaking skyline views from this ultra-luxury penthouse with private terrace, wine cellar, and concierge service.",
    price: "4850000.00",
    address: "1 Skyline Plaza, PH-01",
    city: "Miami",
    state: "FL",
    zipCode: "33132",
    country: "US",
    type: "apartment" as const,
    status: "for_sale" as const,
    category: "luxury" as const,
    bedrooms: 5,
    bathrooms: 5,
    squareFeet: "6200.00",
    yearBuilt: 2023,
    garage: true,
    pool: true,
  },
  {
    title: "Oceanfront Estate",
    description: "Private beachfront mansion with infinity pool, home theater, and direct ocean access.",
    price: "8200000.00",
    address: "420 Ocean Drive",
    city: "Malibu",
    state: "CA",
    zipCode: "90265",
    country: "US",
    type: "house" as const,
    status: "for_sale" as const,
    category: "luxury" as const,
    bedrooms: 7,
    bathrooms: 8,
    squareFeet: "9800.00",
    yearBuilt: 2021,
    garage: true,
    pool: true,
  },
  {
    title: "Grand Hillside Villa",
    description: "Tuscan-inspired hillside villa with panoramic valley views, 3-car garage, and resort-style grounds.",
    price: "3450000.00",
    address: "88 Vista Hermosa Way",
    city: "Beverly Hills",
    state: "CA",
    zipCode: "90210",
    country: "US",
    type: "house" as const,
    status: "for_sale" as const,
    category: "luxury" as const,
    bedrooms: 6,
    bathrooms: 6,
    squareFeet: "7400.00",
    yearBuilt: 2019,
    garage: true,
    pool: true,
  },
  {
    title: "Luxury Sky Residence",
    description: "Full-floor residence in a prestigious tower with private elevator, chef's kitchen, and panoramic city views.",
    price: "2900000.00",
    address: "200 Park Avenue, Floor 42",
    city: "New York",
    state: "NY",
    zipCode: "10166",
    country: "US",
    type: "condo" as const,
    status: "for_sale" as const,
    category: "luxury" as const,
    bedrooms: 4,
    bathrooms: 4,
    squareFeet: "4800.00",
    yearBuilt: 2022,
    garage: true,
    pool: false,
  },

  // ── Affordable ────────────────────────────────────────────────────────────
  {
    title: "Cozy Starter Home",
    description: "Move-in ready 3-bed home on a quiet street. New roof, updated kitchen, and spacious backyard. Perfect for first-time buyers.",
    price: "189000.00",
    address: "314 Elm Street",
    city: "Columbus",
    state: "OH",
    zipCode: "43204",
    country: "US",
    type: "house" as const,
    status: "for_sale" as const,
    category: "affordable" as const,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: "1180.00",
    yearBuilt: 1998,
    garage: false,
    pool: false,
  },
  {
    title: "Value Townhome",
    description: "Bright 2-story townhome with open floor plan, attached garage, and access to community pool. Low HOA fees.",
    price: "215000.00",
    address: "77 Birchwood Lane",
    city: "Indianapolis",
    state: "IN",
    zipCode: "46203",
    country: "US",
    type: "townhouse" as const,
    status: "for_sale" as const,
    category: "affordable" as const,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: "1450.00",
    yearBuilt: 2005,
    garage: true,
    pool: false,
  },
  {
    title: "Budget-Friendly Condo",
    description: "Low-maintenance condo in a well-kept complex near schools and shopping. Ideal starter home or investment.",
    price: "142000.00",
    address: "901 Lakeview Blvd, Unit 3B",
    city: "Memphis",
    state: "TN",
    zipCode: "38103",
    country: "US",
    type: "condo" as const,
    status: "for_sale" as const,
    category: "affordable" as const,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: "870.00",
    yearBuilt: 2001,
    garage: false,
    pool: false,
  },
  {
    title: "Charming Bungalow",
    description: "Classic 3-bed bungalow with original hardwood floors, updated bath, and large covered porch.",
    price: "168000.00",
    address: "52 Maple Avenue",
    city: "Kansas City",
    state: "MO",
    zipCode: "64111",
    country: "US",
    type: "house" as const,
    status: "for_sale" as const,
    category: "affordable" as const,
    bedrooms: 3,
    bathrooms: 1,
    squareFeet: "1050.00",
    yearBuilt: 1955,
    garage: false,
    pool: false,
  },

  // ── New Developments ──────────────────────────────────────────────────────
  {
    title: "Harborview Residences — Phase 1",
    description: "Pre-launch off-plan apartments in the new Harborview district. Choose your layout and finishes. Completion Q4 2026.",
    price: "540000.00",
    address: "Harborview Quarter, Plot 4A",
    city: "San Diego",
    state: "CA",
    zipCode: "92101",
    country: "US",
    type: "apartment" as const,
    status: "for_sale" as const,
    category: "development" as const,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: "1200.00",
    yearBuilt: 2026,
    garage: true,
    pool: true,
  },
  {
    title: "Midtown Green — New Build Townhomes",
    description: "Energy-efficient townhomes in a brand-new community. Rooftop decks, EV charging, and smart-home tech included.",
    price: "620000.00",
    address: "Midtown Green, Block C",
    city: "Nashville",
    state: "TN",
    zipCode: "37203",
    country: "US",
    type: "townhouse" as const,
    status: "for_sale" as const,
    category: "development" as const,
    bedrooms: 3,
    bathrooms: 3,
    squareFeet: "2100.00",
    yearBuilt: 2025,
    garage: true,
    pool: false,
  },
  {
    title: "Riverfront Towers — Pre-Launch",
    description: "Off-plan luxury apartments on the riverfront. Early-bird pricing available until end of month. Completion 2027.",
    price: "780000.00",
    address: "1 Riverfront Boulevard",
    city: "Austin",
    state: "TX",
    zipCode: "78701",
    country: "US",
    type: "apartment" as const,
    status: "for_sale" as const,
    category: "development" as const,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: "1350.00",
    yearBuilt: 2027,
    garage: true,
    pool: true,
  },
  {
    title: "Parkside Homes — Phase 2 Launch",
    description: "New single-family homes with modern interiors, open-plan kitchens, and large private yards. Customisation options available.",
    price: "415000.00",
    address: "Parkside Development, Lot 22",
    city: "Charlotte",
    state: "NC",
    zipCode: "28202",
    country: "US",
    type: "house" as const,
    status: "for_sale" as const,
    category: "development" as const,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: "2400.00",
    yearBuilt: 2025,
    garage: true,
    pool: false,
  },
];

async function main() {
  console.log(`Inserting ${seed.length} properties…`);
  await db.insert(properties).values(seed);
  console.log("Done.");
}

main().catch((e) => { console.error(e); process.exit(1); });
