name: Deploy to Netlify

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Trigger build on Netlify
        run: netlify deploy --trigger --prod --auth "$NETLIFY_AUTH_TOKEN" --site "5ca54cf9-41ef-497b-abe4-e3d9e6d8a482"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
